#! /bin/sh

modpath=/lib/modules/$(uname -r)/extra
mode="664"
group="staff"

device_dynamic_assignation()
{
	module=$1
	device=$2
	minor=$3

	major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

	if [ ! -z ${major} ]; then
		echo "Remove any existing /dev node for /dev/${device}"
		rm -f /dev/${device}
		echo "Add a node for our device at /dev/${device} using mknod"
		mknod /dev/${device} c $major $minor
		echo "Change group owner to ${group}"
		chgrp $group /dev/${device}
		echo "Change access mode to ${mode}"
		chmod $mode  /dev/${device}
	else
		echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
	fi
}

case "$1" in
	start)
		echo "Load modules"
		cd $modpath

		insmod ./scull.ko || exit 1
                device_dynamic_assignation scull scull0 0
		device_dynamic_assignation scull scull1 1
		device_dynamic_assignation scull scull2 2
		device_dynamic_assignation scull scull3 3
		ln -sf scull0 /dev/scull

		device_dynamic_assignation scull scullpipe0 4
                device_dynamic_assignation scull scullpipe1 5
                device_dynamic_assignation scull scullpipe2 6
                device_dynamic_assignation scull scullpipe3 7
		ln -sf scullpipe0 /dev/scullpipe

		device_dynamic_assignation scull scullsingle 8
                device_dynamic_assignation scull sculluid 9
                device_dynamic_assignation scull scullwuid 10
                device_dynamic_assignation scull scullpriv 11
		;;
	stop)
		echo "Unload modules"
		rmmod scull || exit 1
		rm -f /dev/scull /dev/scull[0-3]
		rm -f /dev/scullpipe /dev/scullpipe[0-3]
		rm -f /dev/scullsingle
		rm -f /dev/sculluid
		rm -f /dev/scullwuid
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac
exit 0
